---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      restartPolicy: Always
      containers:
        - name: discord-bot
          image: ghcr.io/effect-ts/discord-bot:main
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.25
              memory: 150Mi
            limits:
              cpu: 1
              memory: 300Mi
          env:
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secrets
                  key: discord-api-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secrets
                  key: openai-key
            - name: OPENAI_ORGANIZATION
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secrets
                  key: openai-org
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secrets
                  key: github-token
            - name: DEBUG
              value: "true"
