apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: discord-bot-secrets
spec:
    suspend: false
    secretTemplates:
        - name: discord-bot-secrets
          stringData:
            discord-api-key: ENC[AES256_GCM,data:vRGG/hFhhs35t+vHXuyZMWHxTWrCRA0cS66eyeHslipY43LoZ7YuyfG2uiVeYYSiWzkAlyQYJfzjRdK7ogXNXZLdoNf+LBC6,iv:IfIaB/Ddd5L8CzgzDgk1GLmtMxvMXBesSt7aGSQ48a0=,tag:aXCpTJqGOx8Ij0QPew4cyg==,type:str]
            github-token: ENC[AES256_GCM,data:jDpc/PywaEpZubQrip5WiKYYejpY9E7kVF81LwtLZcN5tXQ7oGpBeA==,iv:UZT7f8GDP4yljsBahPBOgqfz6PEIEvUoNw7+ZDjygaM=,tag:tRwiaIZNfBFSdL0lyW68BA==,type:str]
            openai-key: ENC[AES256_GCM,data:W8DeLHCgHm6EbOCE3ECm1tl+gb/cG59tAJjL1Rkf93Q0ZuCSFH42w0uV8sucWx9dvp9V,iv:WRZw9mdfTFX0a+JYaV+ITF+nqJ/SNUQZvssi+ClHWuQ=,tag:gCOGhhNqjyw0A5mXeHEJZg==,type:str]
            openai-org: ENC[AES256_GCM,data:Njfs8df+M9d9H7A8+KNzBC+ZdCa3/oceRs6/Eg==,iv:5f0ZBqdpp/JV9v43uKgYrn88eQ6D4sofb1t+ETUF77Y=,tag:/N4ssvJjhfJRHHCLYgbhAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1usc2072gec0plj2q866m0uyeh2rly60xnxts4c3xxh50cwygte8s8avj8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT1VHNUN1OGJHTkhObjU3
            YzFsSS9Yb2lPWnJrZU80OTJjckJSWGlnUXk4CnFSajR6ZGowdTg3S1g1a3JNUUdw
            RUJraS8wOXhualRLSjAwY0tqS1hYcWsKLS0tIDJYTXRJTnRDbUsrWWxCU3VGR1pV
            ZGVpR0VyVFFubnNTZWRFbjl0OTRYcFUKnyEpsf7JqgC6mwOyWrt89VndT9NVdb9b
            aCmL611uonGDYw3wLvkCZD6OLOdiHXHVWPaCx12gATyzGxSTsAFctA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15umcap7zkzq5g32zykcywjk0l6cwldxqk7e46t2ynkkwy0eghuas5rs6t7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocldDRVpXL2tDbGt0NFBn
            alZ2S0Z4dmVJNS8wL05MTE4weGQvV2RQQjBNCkx6NG1wNDJWeTgwMGVJejVHckcr
            VzZycE1pYzF0a3VqUEhnNklPcWRjQTAKLS0tIDNkTnBrVjQwcHZzNnhLcHZTUGFU
            MURvbXdaUkRUekV1ZXMzMGMrTU5JTXMKazF8hCD5xo+Un5Gzus3XOR3aea0aq+zf
            OJntpuPG1mZVEqP7Cy53FCAcw4DHfjS6q5tAVzwDvu+TZBasA7dmXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cqrnyaj8tcu6svafggn5f45juq5lnvghqlqsazvp5pvzt5wa2els9ak7pv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRDZaVWZCNFAwR3FFb2U3
            c2hXVW1rK1IreDhwY2tFUTNBeXFtdXhaelZFCis4ZFpNOU9UZm0xTVl5Nm1OVTJv
            YmtQNmVrKy9JeXk0bEZYVHlFUTBVREEKLS0tIHdnWDMxSkdlR1RiWXZ2SmNvS3RU
            R0pTTWhjQUdCL3Rid3JXNzdLOXVuOE0KpZJ052zzHQ6ZNiDfnFquKRfS7QCUpHWl
            BWqWxFtG5c3JC5YM7kvI0Eg/oNKAV+YLllYYhLSZSEJFU28iUNn/sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pwu309yva6z9qs5z4n5dytns3jze850das6y2qntqq5yc8wzc52sk4nufy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRzRUT29JTkYzQWhnUExn
            YXkvNjc4eE9uL1FRNnRFaDVLdzF2QTJZd1Z3CndYZElMTkF1cWtKZWlGRkpsUTF0
            blhMbXk1dElIYUJQZUVWeVFGRVN1Qk0KLS0tIEV2OWZCYngrcHZrV2VSMkdURzdn
            WDgwYXIwVHZxV292NU8yVUJLUGpvZW8KWqkBb3nuDsoYn359cbO/qSu/iTQC0DEK
            am5vg23J8M96x7Ik8X1xFpL8kJENgIqrjERTkbmoNoEIL1sE5uByYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-13T09:16:43Z"
    mac: ENC[AES256_GCM,data:iWLtltZ2SJi+akfRAkijADpdqCamwrDYGunstLsP77A8eABEvv1fnWKmsco109by46OA9QkiMo+IREvZR4Yc2fZkq9L0RlLYMxIgyxHUo8k7GA6BBakKyOWgyOTCLUtW5XNFX8wmNtWj/d/h/fqcdDyOgX9ffjJ/F3DUeOWa5T8=,iv:r95GRGkZZpcwQT6N4BOOc14Dh9cpzUHnTO9wfOqFhyw=,tag:zuVSEljHZTEctO/M7Q9wSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
