apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: discord-bot-secrets
spec:
    suspend: false
    secretTemplates:
        - name: discord-bot-env
          stringData:
            discord-api-key: ENC[AES256_GCM,data:qRVePrfjlijopzeqwYyN7b09JXan1CHFNGvuJumrGCToDVt8SDHkqEzzqcsz7TJ/zHqXQwtGKyNxUlw=,iv:Gqn4bJqUVPiIuxj6jW3C+ilV35XuKcQBP1ngLV1QQNw=,tag:N22jHqwzFyEKF7TApgu7xw==,type:str]
            github-token: ENC[AES256_GCM,data:iSsj3sUqHseFg2TbSUl7gXi8odrzPZL/sp2o4x5ue6BItFufiuCXSA==,iv:gskxSM2KPV4F8+nildI7pg2Kra5TWuY0A0EhG91ciS4=,tag:Wh1UyM9q19yjfESeAJsWtg==,type:str]
            openai-key: ENC[AES256_GCM,data:NUxGtR3qRWyTAihg1eIWT1+NQkYQuWyu4nwGOXW7nYqSeQKhkT5tj+dOKaXBkrpqRPuQ,iv:TWqCTPpGJtHcc5TsYEWUikwuiT/sQ/1hvyk3lg5vp9A=,tag:nrDKx0EonlwN2yDOjZykHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1usc2072gec0plj2q866m0uyeh2rly60xnxts4c3xxh50cwygte8s8avj8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT1VHNUN1OGJHTkhObjU3
            YzFsSS9Yb2lPWnJrZU80OTJjckJSWGlnUXk4CnFSajR6ZGowdTg3S1g1a3JNUUdw
            RUJraS8wOXhualRLSjAwY0tqS1hYcWsKLS0tIDJYTXRJTnRDbUsrWWxCU3VGR1pV
            ZGVpR0VyVFFubnNTZWRFbjl0OTRYcFUKnyEpsf7JqgC6mwOyWrt89VndT9NVdb9b
            aCmL611uonGDYw3wLvkCZD6OLOdiHXHVWPaCx12gATyzGxSTsAFctA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15umcap7zkzq5g32zykcywjk0l6cwldxqk7e46t2ynkkwy0eghuas5rs6t7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocldDRVpXL2tDbGt0NFBn
            alZ2S0Z4dmVJNS8wL05MTE4weGQvV2RQQjBNCkx6NG1wNDJWeTgwMGVJejVHckcr
            VzZycE1pYzF0a3VqUEhnNklPcWRjQTAKLS0tIDNkTnBrVjQwcHZzNnhLcHZTUGFU
            MURvbXdaUkRUekV1ZXMzMGMrTU5JTXMKazF8hCD5xo+Un5Gzus3XOR3aea0aq+zf
            OJntpuPG1mZVEqP7Cy53FCAcw4DHfjS6q5tAVzwDvu+TZBasA7dmXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cqrnyaj8tcu6svafggn5f45juq5lnvghqlqsazvp5pvzt5wa2els9ak7pv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRDZaVWZCNFAwR3FFb2U3
            c2hXVW1rK1IreDhwY2tFUTNBeXFtdXhaelZFCis4ZFpNOU9UZm0xTVl5Nm1OVTJv
            YmtQNmVrKy9JeXk0bEZYVHlFUTBVREEKLS0tIHdnWDMxSkdlR1RiWXZ2SmNvS3RU
            R0pTTWhjQUdCL3Rid3JXNzdLOXVuOE0KpZJ052zzHQ6ZNiDfnFquKRfS7QCUpHWl
            BWqWxFtG5c3JC5YM7kvI0Eg/oNKAV+YLllYYhLSZSEJFU28iUNn/sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pwu309yva6z9qs5z4n5dytns3jze850das6y2qntqq5yc8wzc52sk4nufy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRzRUT29JTkYzQWhnUExn
            YXkvNjc4eE9uL1FRNnRFaDVLdzF2QTJZd1Z3CndYZElMTkF1cWtKZWlGRkpsUTF0
            blhMbXk1dElIYUJQZUVWeVFGRVN1Qk0KLS0tIEV2OWZCYngrcHZrV2VSMkdURzdn
            WDgwYXIwVHZxV292NU8yVUJLUGpvZW8KWqkBb3nuDsoYn359cbO/qSu/iTQC0DEK
            am5vg23J8M96x7Ik8X1xFpL8kJENgIqrjERTkbmoNoEIL1sE5uByYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T22:22:18Z"
    mac: ENC[AES256_GCM,data:D1Sge1Ll+9Co3DqzMGl50c34d9MFnjtqJfN12wbIWPt6EOOVG0DKYfrbIyMJSGXEnweKVGKsGQBD1Zg8/qkh1VNhsanN9u2asJrzlHO33HpUmQalS6yOf0Sw9bDumEzpj9nRQTNa7FYPRGAlVo0IMKPfnS/2Rbsf1omGDqizb2c=,iv:BmoqXbEkQJ+IsEHv1W6pG6VjSH+aFI5cUMBfTMfvuc8=,tag:ruaCLOarleoeL80fuHF7FA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
