packages:
  - packages/*
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
catalog:
  "@effect/ai-openai": 4.0.0-beta.21
  "@effect/platform-node": 4.0.0-beta.21
  dfx: ^1.0.7
  effect: 4.0.0-beta.21
