packages:
  - packages/*

catalog:
  "@effect/ai-openai": 4.0.0-beta.101
  "@effect/platform-node": 4.0.0-beta.101
  dfx: ^1.0.15
  effect: 4.0.0-beta.101

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build
