packages:
  - packages/*

catalog:
  "@effect/ai-openai": 4.0.0-beta.40
  "@effect/platform-node": 4.0.0-beta.40
  dfx: ^1.0.11
  effect: 4.0.0-beta.40

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build
