---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot

resources:
  - ../../base
  - ./resources/deployment.yaml
  - ./resources/secrets.yaml

commonLabels:
  app: discord-bot
  variant: prod
